# escape=`
FROM opensuse/leap:latest

ARG TEMP_JDK_TAR=open-jdk-11.tar.gz

RUN mkdir /tmp/java && cd $_ && `
    zypper refresh && `
    zypper --non-interactive install tar gzip curl && `
    curl -o $TEMP_JDK_TAR https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz && `
    tar -xf $TEMP_JDK_TAR && `
    cd jdk-11.0.1 && `
    ./bin/jlink --module-path ./jmods/ --compress=2 `
    --add-modules java.base,java.sql,java.desktop,java.management,java.naming,java.logging,java.security.jgss,java.instrument,java.xml,jdk.unsupported `
    --no-header-files --no-man-pages --output /opt/java && `
    cd / && rm -Rf /tmp/*

ENV JAVA_HOME=/opt/java
ENV PATH="$PATH:$JAVA_HOME/bin"

CMD /bin/bash
